"""
Flower FL client implementation for federated learning experiments.

Each FLClient wraps a local model + local dataset partition and
communicates with the Flower server via the NumPyClient interface.

Author: FL Experiment System
Date: 2026
"""

from __future__ import annotations
import logging
from typing import Dict, List, Tuple

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader

import flwr as fl
from flwr.common import NDArrays, Scalar

from src.data.loader import get_client_dataloader, get_client_data_info
from src.models.mnist_cnn import SimpleCNN
from src.models.cifar_cnn import CIFARCNN
from src.utils import tracer


def _build_model(dataset_name: str, device: torch.device) -> nn.Module:
    """
    Instantiate the correct model for the given dataset.

    Args:
        dataset_name: "mnist" or "cifar10".
        device: Torch device to move the model to.

    Returns:
        Model instance on the specified device.

    Raises:
        ValueError: If dataset_name is not supported.
    """
    if dataset_name == "mnist":
        model = SimpleCNN()
    elif dataset_name == "cifar10":
        model = CIFARCNN()
    else:
        raise ValueError(f"Unknown dataset: {dataset_name}")
    return model.to(device)


class FLClient(fl.client.NumPyClient):
    """
    Flower NumPyClient for local training and evaluation.

    Each instance represents one federated client. On creation it loads
    its local data partition from disk (pre-generated by prepare_data.py).
    The server sends global parameters → client trains locally → returns
    updated parameters and metrics.

    Args:
        cid: Client ID string (e.g. "3").
        dataset_name: "mnist" or "cifar10".
        alpha: Dirichlet alpha used for partitioning.
        seed: Partition seed.
        device: Torch device ("cpu" or "cuda").
        local_epochs: Number of local training epochs per round.
        learning_rate: SGD learning rate.
        batch_size: Mini-batch size for local training.
        logger: Optional logger for structured output.

    Attributes:
        model: The local neural network (SimpleCNN or CIFARCNN).
        trainloader: DataLoader for local training data.
        n_train: Number of local training samples.
    """

    def __init__(
        self,
        cid: str,
        dataset_name: str,
        alpha: float,
        seed: int,
        device: torch.device = None,
        local_epochs: int = 3,
        learning_rate: float = 0.01,
        batch_size: int = 32,
        logger: logging.Logger = None,
    ):
        self.cid = cid
        self.dataset_name = dataset_name
        self.alpha = alpha
        self.seed = seed
        self.local_epochs = local_epochs
        self.learning_rate = learning_rate
        self.logger = logger

        if device is None:
            self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        else:
            self.device = device

        # Load local data
        self.trainloader: DataLoader = get_client_dataloader(
            client_id=int(cid),
            dataset_name=dataset_name,
            alpha=alpha,
            seed=seed,
            batch_size=batch_size,
            shuffle=True,
        )
        self.n_train = len(self.trainloader.dataset)

        # Build model
        self.model = _build_model(dataset_name, self.device)

        # TRACER: log client init info
        info = get_client_data_info(int(cid), dataset_name, alpha, seed)
        tracer.trace_client_init(
            cid=int(cid),
            dataset_name=dataset_name,
            n_train=self.n_train,
            input_shape=info["input_shape"],
            classes=info["classes"],
            alpha=alpha,
            logger=logger,
        )
        tracer.trace_model_params(self.model, logger)

    def get_parameters(self, config: Dict) -> NDArrays:
        """
        Return current local model parameters.

        Args:
            config: Configuration dict from server (unused here).

        Returns:
            List of numpy arrays (model parameters in state_dict order).
        """
        return self.model.get_parameters()

    def set_parameters(self, parameters: NDArrays):
        """Load server's global parameters into the local model."""
        self.model.set_parameters(parameters)

    def fit(
        self,
        parameters: NDArrays,
        config: Dict[str, Scalar],
    ) -> Tuple[NDArrays, int, Dict[str, Scalar]]:
        """
        Receive global model, train locally for E epochs, return updates.

        Args:
            parameters: Global model parameters from the server.
            config: Server config dict (can carry round number, etc.).

        Returns:
            Tuple of:
                - Updated parameters (List[np.ndarray])
                - Number of training samples used (int)
                - Metrics dict: {"train_loss": float, "train_accuracy": float}
        """
        self.set_parameters(parameters)
        self.model.train()

        optimizer = torch.optim.SGD(
            self.model.parameters(),
            lr=self.learning_rate,
            momentum=0.9,
        )
        criterion = nn.CrossEntropyLoss()

        total_loss = 0.0
        total_correct = 0
        total_samples = 0

        for _ in range(self.local_epochs):
            for batch_data, batch_labels in self.trainloader:
                batch_data = batch_data.to(self.device)
                batch_labels = batch_labels.to(self.device)

                optimizer.zero_grad()
                outputs = self.model(batch_data)
                loss = criterion(outputs, batch_labels)
                loss.backward()
                optimizer.step()

                total_loss += loss.item() * len(batch_labels)
                preds = outputs.argmax(dim=1)
                total_correct += (preds == batch_labels).sum().item()
                total_samples += len(batch_labels)

        avg_loss = total_loss / total_samples if total_samples > 0 else 0.0
        accuracy = total_correct / total_samples if total_samples > 0 else 0.0

        # TRACER: log a sample tensor from last batch
        tracer.trace_tensor(
            f"client_{self.cid}_last_batch",
            batch_data[0:1],
            self.logger,
        )

        metrics: Dict[str, Scalar] = {
            "train_loss": float(avg_loss),
            "train_accuracy": float(accuracy),
        }

        return self.model.get_parameters(), self.n_train, metrics

    def evaluate(
        self,
        parameters: NDArrays,
        config: Dict[str, Scalar],
    ) -> Tuple[float, int, Dict[str, Scalar]]:
        """
        Evaluate the global model on local data.

        Args:
            parameters: Global model parameters from the server.
            config: Server config dict.

        Returns:
            Tuple of:
                - Loss (float)
                - Number of evaluation samples (int)
                - Metrics dict: {"accuracy": float}
        """
        self.set_parameters(parameters)
        self.model.eval()

        criterion = nn.CrossEntropyLoss()
        total_loss = 0.0
        total_correct = 0
        total_samples = 0

        with torch.no_grad():
            for batch_data, batch_labels in self.trainloader:
                batch_data = batch_data.to(self.device)
                batch_labels = batch_labels.to(self.device)

                outputs = self.model(batch_data)
                loss = criterion(outputs, batch_labels)

                total_loss += loss.item() * len(batch_labels)
                preds = outputs.argmax(dim=1)
                total_correct += (preds == batch_labels).sum().item()
                total_samples += len(batch_labels)

        avg_loss = total_loss / total_samples if total_samples > 0 else 0.0
        accuracy = total_correct / total_samples if total_samples > 0 else 0.0

        return float(avg_loss), total_samples, {"accuracy": float(accuracy)}


def make_client_fn(
    dataset_name: str,
    alpha: float,
    seed: int,
    device: torch.device,
    local_epochs: int = 3,
    learning_rate: float = 0.01,
    batch_size: int = 32,
    logger: logging.Logger = None,
):
    """
    Factory function compatible with fl.simulation.start_simulation().

    Returns a callable that takes a cid string and returns an FLClient.
    This pattern is required by Flower's simulation API.

    Args:
        dataset_name: "mnist" or "cifar10".
        alpha: Dirichlet alpha.
        seed: Partition seed.
        device: Torch device.
        local_epochs: Local training epochs per round.
        learning_rate: SGD learning rate.
        batch_size: Training batch size.
        logger: Optional logger.

    Returns:
        Callable[[str], FLClient]

    Example:
        >>> client_fn = make_client_fn("mnist", 0.1, 42, device)
        >>> fl.simulation.start_simulation(client_fn=client_fn, ...)
    """
    def client_fn(cid: str):
        client = FLClient(
            cid=cid,
            dataset_name=dataset_name,
            alpha=alpha,
            seed=seed,
            device=device,
            local_epochs=local_epochs,
            learning_rate=learning_rate,
            batch_size=batch_size,
            logger=logger,
        )
        # Newer Flower versions (>=1.13) require Client instances, not
        # NumPyClient directly. .to_client() wraps it for compatibility
        # across flwr versions (no-op-equivalent on older versions).
        return client.to_client()
    return client_fn
